name: todo_list
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.2

dev_dependencies: 
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.1

flutter: 
  uses-material-design: true

  assets:
    - assets/anim/empty_box.json

